// ── Task definitions (extracted from app.js for testability) ─────────────────

const CATEGORIES = [
  { id: 'system',       icon: '\u{1F5A5}\uFE0F' },  // 🖥️
  { id: 'user-editor',  icon: '\u{1F464}' },          // 👤
  { id: 'pkg-managers', icon: '\u{1F4E6}' },          // 📦
  { id: 'frameworks',   icon: '\u{1F527}' },          // 🔧
  { id: 'containers',   icon: '\u{1F433}' },          // 🐳
  { id: 'aggressive',   icon: '\u26A0\uFE0F' },       // ⚠️
];

const TASKS = [
  {
    id: 'apt-update',
    name: 'Update System Packages',
    desc: 'Brings all system packages up to date. Uses <code>dnf upgrade</code> on Fedora/RHEL or <code>apt-get update &amp;&amp; upgrade</code> on Debian/Ubuntu.',
    command: 'if command -v dnf &>/dev/null; then dnf upgrade -y; else DEBIAN_FRONTEND=noninteractive apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" || true; fi',
    asRoot: true,
    requires: null,
    category: 'system',
    // No estimateCommand — updates packages, does not free space
  },
  {
    id: 'apt-clean',
    name: 'Clean Old Packages',
    desc: 'Removes orphaned packages and clears package caches. Uses <code>dnf clean all &amp;&amp; dnf autoremove</code> on Fedora/RHEL or <code>apt autoremove &amp;&amp; clean</code> on Debian/Ubuntu.',
    command: 'if command -v dnf &>/dev/null; then dnf clean all && dnf autoremove -y; else DEBIAN_FRONTEND=noninteractive apt -y autoremove; apt -y clean; fi || true',
    asRoot: true,
    requires: null,
    category: 'system',
    estimateCommand: 'du -shc /var/cache/apt/archives /var/cache/dnf 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'journal',
    name: 'Shrink Systemd Journal',
    desc: 'Reduces journal log files to 10 MB and removes entries older than 2 weeks.',
    command: 'journalctl --vacuum-size=10M && journalctl --vacuum-time=2weeks',
    asRoot: true,
    requires: null,
    category: 'system',
    estimateCommand: 'journalctl --disk-usage 2>/dev/null | grep -oE "[0-9.]+[KMGT]" | head -1',
  },
  {
    id: 'tmp',
    name: 'Clean Temporary Files',
    desc: 'Deletes all files in <code>/tmp</code> and <code>/var/tmp</code>.',
    command: 'rm -rf /tmp/* /var/tmp/*',
    asRoot: true,
    requires: null,
    category: 'system',
    estimateCommand: 'du -shc /tmp /var/tmp 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'caches',
    name: 'Clean User Caches',
    desc: 'Clears npm cache, pip cache, and browser caches (Mozilla, Chrome) from your home directory and <code>/root</code>.',
    command: 'for d in /home/* /root; do [ -d "$d" ] && rm -rf "$d/.npm" "$d/.cache/mozilla" "$d/.cache/google-chrome" "$d/.cache/pip" "$d/.cache/pipx" "$d/.cache/composer" 2>/dev/null; done; (pip cache purge 2>/dev/null || pip3 cache purge 2>/dev/null || true); echo "User caches cleaned"',
    asRoot: true,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'du -shc /home/*/.npm /home/*/.cache/mozilla /home/*/.cache/google-chrome /home/*/.cache/pip /home/*/.cache/pipx /home/*/.cache/composer /root/.npm /root/.cache/mozilla /root/.cache/google-chrome /root/.cache/pip /root/.cache/pipx /root/.cache/composer 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'rotated-logs',
    name: 'Clean Old Rotated Logs',
    desc: 'Removes compressed and rotated log files (<code>.gz</code>, <code>.old</code>, <code>.1</code>) from <code>/var/log</code>.',
    command: 'find /var/log -type f \\( -name "*.gz" -o -name "*.old" -o -name "*.1" \\) -delete',
    asRoot: true,
    requires: null,
    category: 'system',
    estimateCommand: 'find /var/log -type f \\( -name "*.gz" -o -name "*.old" -o -name "*.1" \\) 2>/dev/null | xargs -r du -shc 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'truncate-logs',
    name: 'Truncate Active Log Files',
    desc: 'Empties <code>/var/log/syslog</code> and all <code>*.log</code> files in <code>/var/log</code> without deleting them, freeing space while keeping the files intact for continued logging.',
    command: 'truncate -s 0 /var/log/syslog 2>/dev/null; truncate -s 0 /var/log/*.log 2>/dev/null; echo "Log files truncated"',
    asRoot: true,
    requires: null,
    category: 'system',
    estimateCommand: 'du -shc /var/log/syslog /var/log/*.log 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'apt-lists',
    name: 'Clean Apt Package Lists',
    desc: 'Removes cached package lists from <code>/var/lib/apt/lists</code>. They are recreated on the next <code>apt update</code>. (Debian/Ubuntu only)',
    command: 'rm -rf /var/lib/apt/lists/*',
    asRoot: true,
    requires: 'apt',
    category: 'system',
    estimateCommand: 'du -sh /var/lib/apt/lists 2>/dev/null | cut -f1',
  },
  {
    id: 'snap-cache',
    name: 'Clean Snap Cache',
    desc: 'Removes cached snap packages from <code>/var/lib/snapd/cache</code>.',
    command: 'rm -rf /var/lib/snapd/cache/*',
    asRoot: true,
    requires: 'snap',
    category: 'pkg-managers',
    estimateCommand: 'du -sh /var/lib/snapd/cache 2>/dev/null | cut -f1',
  },
  {
    id: 'snap-old-revisions',
    name: 'Remove Old Snap Revisions',
    desc: 'Removes disabled snap revisions sitting in <code>/var/lib/snapd/snaps</code>. Can reclaim several GB.',
    // Escape $ so bash doesn't expand awk fields before awk runs.
    command: "snap list --all 2>/dev/null | awk '/disabled/{print \\$1, \\$3}' | while read snapname revision; do echo \"Removing $snapname revision $revision\"; snap remove \"$snapname\" --revision=\"$revision\" 2>/dev/null; done; echo \"Old snap revisions removed\"",
    asRoot: true,
    requires: 'snap',
    category: 'pkg-managers',
    // No estimateCommand — requires snap list parsing which is fragile across distros
  },
  {
    id: 'vscode-server',
    name: 'Clean VS Code / Cursor / Windsurf Server',
    desc: 'Removes extension caches and log files from <code>~/.vscode-server</code>, <code>~/.cursor-server</code>, and <code>~/.windsurf-server</code>. Preserves extensions and settings.',
    command: 'rm -rf ~/.vscode-server/extensionCache ~/.vscode-server/bin/*/log ~/.vscode-server/data/logs ~/.cursor-server/extensionCache ~/.cursor-server/bin/*/log ~/.cursor-server/data/logs ~/.windsurf-server/extensionCache ~/.windsurf-server/bin/*/log ~/.windsurf-server/data/logs',
    asRoot: false,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'du -shc /home/*/.vscode-server/extensionCache /home/*/.vscode-server/bin/*/log /home/*/.vscode-server/data/logs /home/*/.cursor-server/extensionCache /home/*/.cursor-server/bin/*/log /home/*/.cursor-server/data/logs /home/*/.windsurf-server/extensionCache /home/*/.windsurf-server/bin/*/log /home/*/.windsurf-server/data/logs 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'vscode-old-bins',
    name: 'Clean Old VS Code / Cursor / Windsurf Server Binaries',
    desc: 'Removes old server binaries from <code>~/.vscode-server/bin</code>, <code>~/.cursor-server/bin</code>, and <code>~/.windsurf-server/bin</code>, keeping only the latest version. Each old version is ~200 MB.',
    // Avoid shell-specific globbing errors (e.g. zsh "no matches found") by enumerating directories safely.
    command: 'setopt nonomatch 2>/dev/null || true; set +o nomatch 2>/dev/null || true; for base in ~/.vscode-server/bin ~/.cursor-server/bin ~/.windsurf-server/bin; do [ -d "$base" ] || continue; latest=$(find "$base" -mindepth 1 -maxdepth 1 -type d -exec stat -c "%Y %n" {} + 2>/dev/null | sort -nr | head -1 | awk \'{ $1=""; sub(/^ /,""); print }\'); [ -z "$latest" ] && continue; find "$base" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | while IFS= read -r d; do [ "$d" = "$latest" ] && continue; echo "Removing old binary: $d"; rm -rf "$d"; done; done; echo "Old server binaries cleaned"',
    asRoot: false,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'for base in /home/*/.vscode-server/bin /home/*/.cursor-server/bin /home/*/.windsurf-server/bin /root/.vscode-server/bin /root/.cursor-server/bin /root/.windsurf-server/bin; do [ -d "$base" ] || continue; latest=$(ls -td "$base"/*/ 2>/dev/null | head -1); for d in "$base"/*/; do [ "$d" = "$latest" ] && continue; du -s "$d" 2>/dev/null; done; done | awk "{s+=\\$1}END{if(s>=1048576)printf \\"%.1fG\\",s/1048576;else if(s>=1024)printf \\"%.0fM\\",s/1024;else printf \\"%dK\\",s+0}"',
  },
  {
    id: 'trash',
    name: 'Empty Trash',
    desc: 'Empties the desktop trash folder at <code>~/.local/share/Trash</code>.',
    command: 'rm -rf ~/.local/share/Trash/*',
    asRoot: false,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'du -shc /home/*/.local/share/Trash /root/.local/share/Trash 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'thumbnails',
    name: 'Clean Thumbnail Cache',
    desc: 'Removes cached image thumbnails from <code>~/.cache/thumbnails</code>.',
    command: 'rm -rf ~/.cache/thumbnails/*',
    asRoot: false,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'du -shc /home/*/.cache/thumbnails /root/.cache/thumbnails 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'yarn-cache',
    name: 'Clean Yarn Cache',
    desc: 'Runs <code>yarn cache clean</code> to remove all cached Yarn packages.',
    command: 'yarn cache clean',
    asRoot: false,
    requires: 'yarn',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.cache/yarn /root/.cache/yarn /usr/local/share/.cache/yarn 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'go-cache',
    name: 'Clean Go Module Cache',
    desc: 'Runs <code>go clean -modcache</code> to remove downloaded Go module files.',
    command: 'go clean -modcache',
    asRoot: false,
    requires: 'go',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/go/pkg/mod /root/go/pkg/mod 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'cargo-cache',
    name: 'Clean Cargo/Rust Registry Cache',
    desc: 'Removes cached crate files from <code>~/.cargo/registry/cache</code> and <code>~/.cargo/registry/src</code>.',
    command: 'rm -rf ~/.cargo/registry/cache/* ~/.cargo/registry/src/*',
    asRoot: false,
    requires: null,
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.cargo/registry/cache /home/*/.cargo/registry/src /root/.cargo/registry/cache /root/.cargo/registry/src 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'laravel-clean',
    name: 'Clean Laravel Logs &amp; Cache',
    desc: 'Finds Laravel projects under <code>/home</code> and <code>/var/www</code> and removes log files from <code>storage/logs</code> and disk cache from <code>storage/framework/cache/data</code> and <code>storage/framework/views</code>.',
    command: 'find /home /var/www -maxdepth 5 -name artisan -type f 2>/dev/null | while IFS= read -r artisan; do dir=$(dirname "$artisan"); if [ -d "$dir/storage/logs" ]; then find "$dir/storage/logs" -name "*.log*" -type f -delete 2>/dev/null && echo "Cleaned logs: $dir"; fi; if [ -d "$dir/storage/framework/cache/data" ]; then rm -rf "$dir/storage/framework/cache/data/"* 2>/dev/null && echo "Cleaned cache: $dir"; fi; if [ -d "$dir/storage/framework/views" ]; then find "$dir/storage/framework/views" -name "*.php" -type f -delete 2>/dev/null && echo "Cleaned views: $dir"; fi; done; echo "Laravel cleanup complete"',
    asRoot: true,
    requires: null,
    category: 'frameworks',
    estimateCommand: 'find /home /var/www -maxdepth 5 -name artisan -type f 2>/dev/null | while IFS= read -r a; do d=$(dirname "$a"); du -s "$d/storage/logs" "$d/storage/framework/cache/data" "$d/storage/framework/views" 2>/dev/null; done | awk "{s+=\\$1}END{if(s>=1048576)printf \\"%.1fG\\",s/1048576;else if(s>=1024)printf \\"%.0fM\\",s/1024;else printf \\"%dK\\",s+0}"',
  },
  {
    id: 'framework-caches',
    name: 'Clean Framework Build Caches',
    desc: 'Finds JS/TS projects and removes regenerable build caches: <code>.next/cache</code>, <code>.angular/cache</code>, <code>node_modules/.cache</code>, <code>.svelte-kit</code>, <code>.tsbuildinfo</code> files, and more.',
    command: [
      'echo "Cleaning node_modules/.cache..."',
      'find /home /var/www -maxdepth 8 -type d -name .cache -path "*/node_modules/.cache" -exec rm -rf {} + 2>/dev/null',
      'echo "Cleaning .next/cache..."',
      'find /home /var/www -maxdepth 8 -type d -name cache -path "*/.next/cache" -exec rm -rf {} + 2>/dev/null',
      'echo "Cleaning .angular/cache..."',
      'find /home /var/www -maxdepth 8 -type d -name cache -path "*/.angular/cache" -exec rm -rf {} + 2>/dev/null',
      'echo "Cleaning .svelte-kit..."',
      'find /home /var/www -maxdepth 8 -type d -name .svelte-kit -exec rm -rf {} + 2>/dev/null',
      'echo "Cleaning .nuxt caches..."',
      'find /home /var/www -maxdepth 8 -type d \\( -path "*/.nuxt/.cache" -o -path "*/.nuxt/analyze" \\) -exec rm -rf {} + 2>/dev/null',
      'echo "Cleaning .parcel-cache..."',
      'find /home /var/www -maxdepth 8 -type d -name .parcel-cache -exec rm -rf {} + 2>/dev/null',
      'echo "Cleaning .turbo..."',
      'find /home /var/www -maxdepth 8 -type d -name .turbo -exec rm -rf {} + 2>/dev/null',
      'echo "Cleaning .tsbuildinfo files..."',
      'find /home /var/www -maxdepth 8 -type f -name "*.tsbuildinfo" -delete 2>/dev/null',
      'echo "Framework build caches cleaned"',
    ].join('; '),
    asRoot: true,
    requires: null,
    category: 'frameworks',
    estimateCommand: 'find /home /var/www -maxdepth 8 -type d \\( -path "*/node_modules/.cache" -o -path "*/.next/cache" -o -path "*/.angular/cache" -o -name .svelte-kit -o -name .parcel-cache -o -name .turbo \\) 2>/dev/null | xargs -r du -shc 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'rust-target',
    name: 'Clean Rust Build Artifacts',
    desc: 'Finds Rust projects under <code>/home</code> and removes their <code>target/</code> directories. Each project can have 1&ndash;10 GB in build output. Rebuilt on next <code>cargo build</code>.',
    command: 'find /home /root -maxdepth 6 -name Cargo.toml -type f 2>/dev/null | while IFS= read -r f; do dir=$(dirname "$f")/target; if [ -d "$dir" ]; then echo "Removing: $dir"; rm -rf "$dir"; fi; done; echo "Rust build artifacts cleaned"',
    asRoot: true,
    requires: null,
    category: 'frameworks',
    estimateCommand: 'find /home /root -maxdepth 6 -name Cargo.toml -type f 2>/dev/null | while IFS= read -r f; do d=$(dirname "$f")/target; [ -d "$d" ] && du -s "$d" 2>/dev/null; done | awk "{s+=\\$1}END{if(s>=1048576)printf \\"%.1fG\\",s/1048576;else if(s>=1024)printf \\"%.0fM\\",s/1024;else printf \\"%dK\\",s+0}"',
  },
  {
    id: 'android-cache',
    name: 'Clean Android SDK &amp; Gradle Build Cache',
    desc: 'Removes <code>~/.android/cache</code>, <code>~/.android/build-cache</code>, and Gradle project <code>build/</code> directories. Mobile devs can have 5&ndash;20 GB here.',
    command: 'for d in /home/* /root; do [ -d "$d" ] && rm -rf "$d/.android/cache" "$d/.android/build-cache" 2>/dev/null; done; find /home /root -maxdepth 6 \\( -name "build.gradle" -o -name "build.gradle.kts" \\) -type f 2>/dev/null | while IFS= read -r f; do dir=$(dirname "$f")/build; if [ -d "$dir" ]; then echo "Removing: $dir"; rm -rf "$dir"; fi; done; echo "Android/Gradle build cache cleaned"',
    asRoot: true,
    requires: null,
    category: 'frameworks',
    estimateCommand: 'du -shc /home/*/.android/cache /home/*/.android/build-cache /root/.android/cache /root/.android/build-cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'python-bytecode',
    name: 'Remove Python Bytecode',
    desc: 'Removes all <code>__pycache__</code> directories and <code>*.pyc</code> files under <code>/home</code>. Rebuilt automatically on next import.',
    command: 'find /home -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null; find /home -type f -name "*.pyc" -delete 2>/dev/null; echo "Python bytecode cleaned"',
    asRoot: true,
    requires: null,
    category: 'frameworks',
    estimateCommand: 'find /home -type d -name __pycache__ 2>/dev/null | xargs -r du -shc 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'docker-prune',
    name: 'Clean Docker Dangling Artifacts',
    desc: 'Removes dangling (untagged) images, unused networks, and stale build cache. All named/tagged images, containers, and volumes are preserved.',
    command: 'docker info >/dev/null 2>&1 || { echo "Docker CLI found but daemon is not running — skipping Docker cleanup"; exit 0; }; docker image prune -f 2>/dev/null && docker network prune -f 2>/dev/null && docker builder prune -f 2>/dev/null && echo "Docker dangling artifacts cleaned"',
    asRoot: false,
    requires: 'docker',
    category: 'containers',
    // No estimateCommand — docker system df output is complex and fragile to parse
  },
  {
    id: 'pip-cache',
    name: 'Clean Pip Cache Directory',
    desc: 'Removes downloaded pip packages from <code>~/.cache/pip</code>.',
    command: 'rm -rf ~/.cache/pip/*',
    asRoot: false,
    requires: null,
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.cache/pip /root/.cache/pip 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'pnpm-cache',
    name: 'Clean pnpm Store',
    desc: 'Prunes the pnpm content-addressable store and removes temp files.',
    command: 'pnpm store prune 2>/dev/null; rm -rf ~/.local/share/pnpm/store/v3/tmp/* 2>/dev/null; echo "pnpm store pruned"',
    asRoot: false,
    requires: 'pnpm',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.local/share/pnpm/store /root/.local/share/pnpm/store 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'composer-cache',
    name: 'Clean Composer Cache',
    desc: 'Clears the PHP Composer download cache from <code>~/.cache/composer</code>.',
    command: 'composer clear-cache 2>/dev/null || rm -rf ~/.cache/composer/* ~/.composer/cache/* 2>/dev/null; echo "Composer cache cleaned"',
    asRoot: false,
    requires: 'composer',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.cache/composer /home/*/.composer/cache /root/.cache/composer /root/.composer/cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'maven-cache',
    name: 'Clean Maven Cache',
    desc: 'Removes cached Maven artifacts from <code>~/.m2/repository</code>. Can reclaim 5&ndash;15 GB for active Java projects.',
    command: 'rm -rf ~/.m2/repository/*; echo "Maven cache cleaned"',
    asRoot: false,
    requires: 'mvn',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.m2/repository /root/.m2/repository 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'gradle-cache',
    name: 'Clean Gradle Cache',
    desc: 'Removes Gradle build caches and wrapper distributions from <code>~/.gradle</code>.',
    command: 'rm -rf ~/.gradle/caches/* ~/.gradle/wrapper/dists/*; echo "Gradle cache cleaned"',
    asRoot: false,
    requires: 'gradle',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.gradle/caches /home/*/.gradle/wrapper/dists /root/.gradle/caches /root/.gradle/wrapper/dists 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'sbt-ivy-cache',
    name: 'Clean sbt / Ivy Cache',
    desc: 'Removes Scala build caches from <code>~/.ivy2/cache</code> and <code>~/.sbt/boot</code>. Scala devs can accumulate 1&ndash;5 GB here. Re-downloaded on next build.',
    command: 'rm -rf ~/.ivy2/cache/* ~/.sbt/boot/* 2>/dev/null; echo "sbt/Ivy cache cleaned"',
    asRoot: false,
    requires: 'sbt',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.ivy2/cache /home/*/.sbt/boot /root/.ivy2/cache /root/.sbt/boot 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'conan-cache',
    name: 'Clean Conan C++ Cache',
    desc: 'Removes Conan C++ package manager caches from <code>~/.conan/data</code> and <code>~/.conan2/p</code>. Can be 1&ndash;5 GB for active C++ projects. Re-downloaded on next build.',
    command: 'rm -rf ~/.conan/data/* ~/.conan2/p/* 2>/dev/null; echo "Conan cache cleaned"',
    asRoot: false,
    requires: 'conan',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.conan/data /home/*/.conan2/p /root/.conan/data /root/.conan2/p 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'conda-cache',
    name: 'Clean Conda Cache',
    desc: 'Removes unused Conda packages, tarballs, and cached downloads.',
    command: 'conda clean --all -y 2>/dev/null || true; echo "Conda cache cleaned"',
    asRoot: false,
    requires: 'conda',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/miniconda3/pkgs /home/*/anaconda3/pkgs /home/*/.conda/pkgs /root/miniconda3/pkgs /root/anaconda3/pkgs 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'gem-cache',
    name: 'Clean Ruby Gems Cache',
    desc: 'Runs <code>gem cleanup</code> and removes cached gem files from <code>~/.gem</code>.',
    command: 'gem cleanup 2>/dev/null; rm -rf ~/.gem/ruby/*/cache/* 2>/dev/null; echo "Gem cache cleaned"',
    asRoot: false,
    requires: 'gem',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.gem/ruby/*/cache /root/.gem/ruby/*/cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'nuget-cache',
    name: 'Clean NuGet Cache',
    desc: 'Clears .NET NuGet package caches from <code>~/.nuget</code> and local share.',
    command: 'dotnet nuget locals all --clear 2>/dev/null || rm -rf ~/.nuget/packages/* ~/.local/share/NuGet/* 2>/dev/null; echo "NuGet cache cleaned"',
    asRoot: false,
    requires: 'dotnet',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.nuget/packages /home/*/.local/share/NuGet /root/.nuget/packages /root/.local/share/NuGet 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'deno-cache',
    name: 'Clean Deno Cache',
    desc: 'Removes cached remote modules and compiled files from <code>~/.cache/deno</code> and <code>~/.deno/cache</code>.',
    command: 'rm -rf ~/.cache/deno/* ~/.deno/cache/* 2>/dev/null; echo "Deno cache cleaned"',
    asRoot: false,
    requires: 'deno',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.cache/deno /home/*/.deno/cache /root/.cache/deno /root/.deno/cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'bun-cache',
    name: 'Clean Bun Cache',
    desc: 'Removes cached packages from <code>~/.bun/install/cache</code>.',
    command: 'rm -rf ~/.bun/install/cache/* 2>/dev/null; echo "Bun cache cleaned"',
    asRoot: false,
    requires: 'bun',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.bun/install/cache /root/.bun/install/cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'dart-cache',
    name: 'Clean Dart/Flutter Pub Cache',
    desc: 'Clears the Dart/Flutter package cache from <code>~/.pub-cache</code>.',
    command: 'rm -rf ~/.pub-cache/hosted/pub.dev/*/.cache 2>/dev/null; dart pub cache clean -f 2>/dev/null || rm -rf ~/.pub-cache/_temp/* 2>/dev/null; echo "Pub cache cleaned"',
    asRoot: false,
    requires: 'dart',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.pub-cache /root/.pub-cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'brew-cache',
    name: 'Clean Homebrew/Linuxbrew Cache',
    desc: 'Removes old downloads and formula from <code>~/.cache/Homebrew</code>.',
    command: 'brew cleanup --prune=all -s 2>/dev/null; rm -rf ~/.cache/Homebrew/* 2>/dev/null; echo "Homebrew cache cleaned"',
    asRoot: false,
    requires: 'brew',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.cache/Homebrew /root/.cache/Homebrew /home/linuxbrew/.linuxbrew/cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'db-logs',
    name: 'Clean Database Logs',
    desc: 'Removes MySQL/MariaDB and PostgreSQL log files from <code>/var/log</code>. Safe to clean on dev instances.',
    command: 'find /var/log/mysql /var/log/postgresql -type f 2>/dev/null -delete; rm -rf /var/lib/mysql/*.log.* 2>/dev/null; echo "Database logs cleaned"',
    asRoot: true,
    requires: null,
    category: 'containers',
    estimateCommand: 'du -shc /var/log/mysql /var/log/postgresql /var/lib/mysql/*.log.* 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'k8s-cache',
    name: 'Clean Kubernetes &amp; Helm Cache',
    desc: 'Removes kubectl API discovery cache from <code>~/.kube/cache</code> and Helm chart cache from <code>~/.cache/helm</code>.',
    command: 'rm -rf ~/.kube/cache/* ~/.cache/helm/* 2>/dev/null; echo "Kubernetes caches cleaned"',
    asRoot: false,
    requires: null,
    category: 'containers',
    estimateCommand: 'du -shc /home/*/.kube/cache /home/*/.cache/helm /root/.kube/cache /root/.cache/helm 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'terraform-cache',
    name: 'Clean Terraform Plugin Cache',
    desc: 'Removes Terraform provider/plugin caches from <code>~/.terraform.d/plugin-cache</code> and project-level <code>.terraform/providers</code>. Providers can be 100&ndash;500 MB each. Re-downloaded on next <code>terraform init</code>.',
    command: 'for d in /home/* /root; do [ -d "$d" ] && rm -rf "$d/.terraform.d/plugin-cache"/* 2>/dev/null; done; find /home -maxdepth 8 -type d -name providers -path "*/.terraform/providers" -exec rm -rf {} + 2>/dev/null; echo "Terraform cache cleaned"',
    asRoot: true,
    requires: 'terraform',
    category: 'containers',
    estimateCommand: 'du -shc /home/*/.terraform.d/plugin-cache /root/.terraform.d/plugin-cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'minikube-cache',
    name: 'Clean Minikube Cache',
    desc: 'Removes cached ISO images, Kubernetes binaries, and container images from <code>~/.minikube/cache</code>. Can be 1&ndash;3 GB. Re-downloaded on next <code>minikube start</code>.',
    command: 'rm -rf ~/.minikube/cache/* 2>/dev/null; echo "Minikube cache cleaned"',
    asRoot: false,
    requires: 'minikube',
    category: 'containers',
    estimateCommand: 'du -shc /home/*/.minikube/cache /root/.minikube/cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'editor-swap',
    name: 'Clean Vim/Neovim Swap &amp; Undo Files',
    desc: 'Removes leftover swap, undo, and shada files from Vim and Neovim.',
    command: 'rm -rf ~/.local/share/nvim/swap/* ~/.local/share/nvim/shada/* ~/.vim/undo/* ~/.vim/swap/* 2>/dev/null; find ~ -maxdepth 1 -name ".*.swp" -delete 2>/dev/null; echo "Editor swap/undo files cleaned"',
    asRoot: false,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'du -shc /home/*/.local/share/nvim/swap /home/*/.local/share/nvim/shada /home/*/.vim/undo /home/*/.vim/swap /root/.local/share/nvim/swap /root/.local/share/nvim/shada /root/.vim/undo /root/.vim/swap 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'git-gc',
    name: 'Compact Git Repositories',
    desc: 'Finds all git repos under <code>/home</code> and aggressively compacts them: expires reflog entries and repacks objects with maximum compression. Branches, tags, and reachable commits are untouched. Reflog recovery history is lost.',
    command: 'find /home -maxdepth 6 -type d -name .git 2>/dev/null | while IFS= read -r gitdir; do repo=$(dirname "$gitdir"); echo "Compacting: $repo"; git -C "$repo" reflog expire --expire=now --all 2>/dev/null; git -C "$repo" gc --prune=now --aggressive 2>/dev/null; done; echo "Git compaction complete"',
    asRoot: true,
    requires: null,
    category: 'containers',
    // No estimateCommand — compaction savings are unpredictable
  },
  {
    id: 'shell-caches',
    name: 'Clean Shell Completion Caches',
    desc: 'Removes Zsh completion dumps (<code>~/.zcompdump*</code>), oh-my-zsh cache, and Zsh session files. Rebuilt automatically.',
    command: 'rm -f ~/.zcompdump* 2>/dev/null; rm -rf ~/.oh-my-zsh/cache/* 2>/dev/null; rm -rf ~/.zsh_sessions/* 2>/dev/null; echo "Shell caches cleaned"',
    asRoot: false,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'du -shc /home/*/.oh-my-zsh/cache /home/*/.zsh_sessions /root/.oh-my-zsh/cache /root/.zsh_sessions 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'jupyter-runtime',
    name: 'Clean Jupyter Runtime Files',
    desc: 'Removes leftover kernel connection files and runtime data from <code>~/.local/share/jupyter/runtime</code>.',
    command: 'rm -rf ~/.local/share/jupyter/runtime/* 2>/dev/null; echo "Jupyter runtime cleaned"',
    asRoot: false,
    requires: null,
    category: 'user-editor',
    estimateCommand: 'du -shc /home/*/.local/share/jupyter/runtime /root/.local/share/jupyter/runtime 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'ccache-clean',
    name: 'Clean ccache',
    desc: 'Clears the C/C++ compiler cache from <code>~/.ccache</code>. Can reclaim several GB.',
    command: 'ccache -C 2>/dev/null || rm -rf ~/.ccache/* 2>/dev/null; echo "ccache cleaned"',
    asRoot: false,
    requires: 'ccache',
    category: 'pkg-managers',
    estimateCommand: 'du -shc /home/*/.ccache /root/.ccache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'bazel-cache',
    name: 'Clean Bazel Cache',
    desc: 'Removes Bazel build cache from <code>~/.cache/bazel</code>. Can be 10+ GB.',
    command: 'rm -rf ~/.cache/bazel/* 2>/dev/null; echo "Bazel cache cleaned"',
    asRoot: false,
    requires: 'bazel',
    category: 'frameworks',
    estimateCommand: 'du -shc /home/*/.cache/bazel /root/.cache/bazel 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'core-dumps',
    name: 'Clean Core Dumps &amp; Crash Reports',
    desc: 'Removes crash reports from <code>/var/crash</code> and coredumps from <code>/var/lib/systemd/coredump</code>.',
    command: 'rm -rf /var/crash/* /var/lib/systemd/coredump/* 2>/dev/null; echo "Core dumps cleaned"',
    asRoot: true,
    requires: null,
    category: 'system',
    estimateCommand: 'du -shc /var/crash /var/lib/systemd/coredump 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'old-kernels',
    name: 'Remove Old Kernel Packages',
    desc: 'WSL uses its own kernel, so any installed <code>linux-image</code>, <code>linux-headers</code>, or <code>linux-modules</code> packages are dead weight. (Debian/Ubuntu only)',
    command: 'dpkg -l "linux-image-*" 2>/dev/null | awk "/^ii/{print \\$2}" | xargs -r apt-get -y purge 2>/dev/null; dpkg -l "linux-headers-*" 2>/dev/null | awk "/^ii/{print \\$2}" | xargs -r apt-get -y purge 2>/dev/null; dpkg -l "linux-modules-*" 2>/dev/null | awk "/^ii/{print \\$2}" | xargs -r apt-get -y purge 2>/dev/null; echo "Old kernel packages removed"',
    asRoot: true,
    requires: 'apt',
    category: 'system',
    estimateCommand: 'du -shc /lib/modules /usr/src/linux-headers-* 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'font-cache',
    name: 'Clean Font Cache',
    desc: 'Removes font cache files from <code>/var/cache/fontconfig</code> and <code>~/.cache/fontconfig</code>. Rebuilt automatically on demand.',
    command: 'rm -rf /var/cache/fontconfig/* ~/.cache/fontconfig/* 2>/dev/null; echo "Font cache cleaned"',
    asRoot: true,
    requires: null,
    category: 'system',
    estimateCommand: 'du -shc /var/cache/fontconfig /home/*/.cache/fontconfig /root/.cache/fontconfig 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'fstrim',
    name: 'Filesystem TRIM',
    desc: 'Runs <code>fstrim</code> to inform the virtual disk which blocks are free. Makes VHDX compaction dramatically more effective. Falls back to zero-filling free space if TRIM is not supported.',
    command: 'fstrim / 2>/dev/null || (echo "fstrim not supported, zero-filling free space..." && dd if=/dev/zero of=/zero.fill bs=1M 2>/dev/null; rm -f /zero.fill); echo "TRIM complete"',
    asRoot: true,
    requires: null,
    category: 'system',
    // No estimateCommand — marks free blocks, does not delete anything
  },
  {
    id: 'shell-history',
    name: 'Trim Shell History',
    desc: 'Trims <code>~/.bash_history</code>, <code>~/.zsh_history</code>, and <code>~/.local/share/fish/fish_history</code> to the last 10 MB. Only touches files larger than 10 MB.',
    command: 'for f in /home/*/.bash_history /home/*/.zsh_history /home/*/.local/share/fish/fish_history /root/.bash_history /root/.zsh_history /root/.local/share/fish/fish_history; do [ -f "$f" ] || continue; size=$(stat -c%s "$f" 2>/dev/null); if [ "$size" -gt 10485760 ] 2>/dev/null; then tail -c 10485760 "$f" > "$f.tmp" && mv "$f.tmp" "$f" && echo "Trimmed: $f"; fi; done; echo "Shell history trimmed"',
    asRoot: true,
    requires: null,
    aggressive: true,
    category: 'aggressive',
    estimateCommand: 'du -shc /home/*/.bash_history /home/*/.zsh_history /home/*/.local/share/fish/fish_history /root/.bash_history /root/.zsh_history /root/.local/share/fish/fish_history 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'general-cache',
    name: 'Clean All User Caches',
    desc: 'Blanket cleanup of the entire <code>~/.cache</code> directory. Catches miscellaneous app caches not covered by other tasks.',
    command: 'du -sh ~/.cache 2>/dev/null; rm -rf ~/.cache/*; echo "User cache cleaned"',
    asRoot: false,
    requires: null,
    aggressive: true,
    category: 'aggressive',
    estimateCommand: 'du -shc /home/*/.cache /root/.cache 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'man-pages',
    name: 'Remove Man Pages &amp; Docs',
    desc: 'Deletes offline manual pages, documentation, and info files from <code>/usr/share</code>. Saves 200&ndash;400 MB. Regenerated when packages are reinstalled.',
    command: 'rm -rf /usr/share/man/* /usr/share/doc/* /usr/share/info/*; echo "Man pages and docs removed"',
    asRoot: true,
    requires: null,
    aggressive: true,
    category: 'aggressive',
    estimateCommand: 'du -shc /usr/share/man /usr/share/doc /usr/share/info 2>/dev/null | tail -1 | cut -f1',
  },
  {
    id: 'locales',
    name: 'Remove Unused Locales',
    desc: 'Removes all locale data except English from <code>/usr/share/locale</code>. Saves 100+ MB. Do not use if you need non-English locales.',
    command: 'find /usr/share/locale -maxdepth 1 -mindepth 1 -type d ! -name "en*" -exec rm -rf {} + 2>/dev/null; echo "Unused locales removed"',
    asRoot: true,
    requires: null,
    aggressive: true,
    category: 'aggressive',
    estimateCommand: 'find /usr/share/locale -maxdepth 1 -mindepth 1 -type d ! -name "en*" 2>/dev/null | xargs -r du -shc 2>/dev/null | tail -1 | cut -f1',
  },
];

// Export for Node.js/test environments; in browser these are just globals
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TASKS, CATEGORIES };
}
